version: '3.8'
services:
  api:
    container_name: ${DB_NAME}-api-container
    build:
      context: .
      target: development
      dockerfile: ./dockerfile
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: ${DB_NAME}-mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
  adminer:
    image: adminer
    container_name: ${DB_NAME}-adminer-container
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: 'pappu687'
    depends_on:
      - db
