version: '3.8'
services:
  api:
    container_name: ${DB_NAME}-api-container
    build:
      context: .
      target: development
      dockerfile: ./dockerfile
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/:/var/lib/postgresql/data/
    container_name: ${DB_NAME}-postgres-container
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  adminer:
    image: adminer
    container_name: ${DB_NAME}-adminer-container
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: 'pappu687'
    depends_on:
      - db
